[package]
name = "fleet"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]

[features]
# To activate YAML support
# default = ["yaml"]
default = []

yaml = []

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.6"
ssh2 = "0.3"
clap = "2.23"